project:
  type: website
  output-dir: ../docs

website:
  title: "Analyzing U.S. State Sentiments"
  sidebar:
    style: floating  # Options: "docked" or "floating"
    contents:
      - href: index.qmd
        text: Introduction
      - href: eda.qmd
        text: EDA
      - href: nlp.qmd
        text: NLP
      - href: ml.qmd
        text: ML
      - href: summary.qmd
        text: Summary
      - href: https://github.com/gu-dsan6000/fall-2024-project-team-29
        text: Code
  page-footer:
    left: |
      Content Â© 2024 by Isfar Baset, Ronan Corgel, Sai Prerana Mandalika, and Powell Sheagren <br>
      Licensed under [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Made with [R](https://www.r-project.org) and [Quarto](https://quarto.org)<br>
      [View source on GitHub](https://github.com/anly503/lab-2.1)

format:
  html:
    theme: cosmo
    css: style.css
    toc: true